outputs = { Targets = ["eDP-1"] }
position = "Top"

[logging]
level = "error"

[modules]
left = [ "leftlogo", [ "Workspaces", "WindowTitle" ] ]
center = [ "Tempo" ]
right = [ "SystemInfo", "MediaPlayer", [ "Tray", "SingBox", "Privacy", "Settings" ] ]

#[updates]
#check_cmd = "checkupdates; paru -Qua"
#update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'
#interval = 3600

[workspaces]
visibility_mode = "All"
group_by_monitor = false
enable_workspace_filling = true
[window_title]
mode = "Class"
truncate_title_after_length = 40

######## System Info ########
[system_info]
indicators = [ "Cpu", "Memory", "Temperature", "IpAddress" ]
interval = 10

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"

[tempo]
clock_format = "%Y-%m-%d %A %H:%M:%S %p"
#formats = [
#    "%a %d %b %R",         # Mon 23 Dec 14:30
#    "%Y-%m-%d %H:%M:%S",   # 2024-12-23 14:30:45
#    "%d/%m/%Y %I:%M %p",   # 23/12/2024 02:30 PM
#    "%A, %B %d, %Y",       # Monday, December 23, 2024
#    "%H:%M:%S",            # 14:30:45 (updates every second)
#    "%x",                  # Locale date (e.g., 12/23/24)
#    "%X",                  # Locale time (e.g., 14:30:45)
#]
timezones = [ "Asia/Shanghai" ]
weather_location = { City = "Nanjing" }
weather_indicator = "IconAndTemperature"

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"
battery_format = "IconAndTime"
keyboard_backlight_slider = true
peripheral_battery_format = "Icon"
audio_indicator_format = "Icon"
microphone_indicator_format = "Icon"
network_indicator_format = "Icon"
bluetooth_indicator_format = "Icon"
brightness_indicator_format = "Icon"
indicators = [ "IdleInhibitor", "PowerProfile", "Audio", "Microphone", "Bluetooth", "Network", "Vpn", "Battery", "Brightness" ]

[[settings.CustomButton]]
name = "Virtual Keyboard"
icon = "⌨️"
command = "/path/to/toggle-keyboard.sh"
status_command = "/path/to/check-keyboard-status.sh"
tooltip = "Toggle On-Screen Keyboard"

[[CustomModule]]
name = "SingBox"
icon = "󰏗 "
type = "Button"
command = "systemctl restart singbox"
on_right_click = "systemctl stop singbox"

[[CustomModule]]
name = "leftlogo"
type = "Button"
icon = "EVANGELION 󱤓 󰫍󰫍󰫍 "
[[CustomModule]]
name = "left_head"
type = "Button"
icon = ""
[[CustomModule]]
name = "left_tail"
type = "Button"
icon = ""
[[CustomModule]]
name = "right_head"
type = "Button"
icon = ""
[[CustomModule]]
name = "right_tail"
type = "Button"
icon = ""

##################### theme #######################
[appearance]
opacity = 0.9
scale_factor = 1.5

success_color = "#50FA7B"
danger_color = "#FF5555"
text_color = "#BD93F9"

workspace_colors = [ "#BD93F9", "#50FA7B" ]
special_workspace_colors = [ "#BD93F9", "#50FA7B" ]

[appearance.bar]
surface = "solid"

[appearance.primary_color]
base = "#FF79C6"

[appearance.background_color]
base = "#282A36"
