wallpaper {
	monitor = eDP-1
	path = /home/evi1_f4iry/Pictures/wallpaper/ROG_X_EVANGELION_(Kangi_version).jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-1
	path = /home/evi1_f4iry/Pictures/wallpaper/pwndefend_wall5.PNG
	fit_mode = cover
}

wallpaper {
	monitor =
	path = /home/evi1_f4iry/Pictures/wallpaper/pwn_defend_wall10_pewpew.png
	fit_mode = cover
}

# 在壁纸上渲染标语
splash = false
# 标语位置偏移
#splash_offset = 
# 完全关闭ipc以节省性能
ipc = false
